<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2z7j3ac\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2z7j3ac/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2z7j3ac.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2z7j3ac\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2z7j3ac\appProdProjectContainer(array(
    'container.build_hash' => '2z7j3ac',
    'container.build_id' => '6daeab2b',
    'container.build_time' => 1539468341,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2z7j3ac');
